import {
  Table,
  Column,
  CreatedAt,
  UpdatedAt,
  Model,
  PrimaryKey,
  AutoIncrement,
  DataType,
  BelongsTo,
  ForeignKey
} from "sequelize-typescript";
import Company from "./Company";
import CrmLead from "./CrmLead";
import Cliente from "./Cliente";
import User from "./User";
import CrmTaskCategory from "./CrmTaskCategory";
import CrmTaskStage from "./CrmTaskStage";

@Table({ tableName: "CrmTasks" })
class CrmTask extends Model<CrmTask> {
  @PrimaryKey
  @AutoIncrement
  @Column
  id: number;

  @ForeignKey(() => Company)
  @Column
  companyId: number;

  @ForeignKey(() => CrmLead)
  @Column
  leadId?: number;

  @ForeignKey(() => Cliente)
  @Column
  clienteId?: number;

  @ForeignKey(() => User)
  @Column
  userId: number;

  @ForeignKey(() => CrmTaskCategory)
  @Column
  categoryId?: number;

  @ForeignKey(() => CrmTaskStage)
  @Column
  stageId?: number;

  @Column(DataType.STRING(255))
  title: string;

  @Column(DataType.TEXT)
  description?: string;

  @Column(DataType.DATE)
  dueDate?: Date;

  @Column(DataType.STRING(20))
  status: string;

  @Column(DataType.STRING(20))
  priority: string;

  @Column(DataType.DATE)
  completedAt?: Date;

  @Column(DataType.STRING(20))
  recurrence?: string;

  @ForeignKey(() => CrmTask)
  @Column
  parentTaskId?: number;

  @Column(DataType.DATE)
  nextOccurrence?: Date;

  @Column(DataType.INTEGER)
  reminderDays?: number;

  @Column(DataType.BOOLEAN)
  isAutoGenerated: boolean;

  @CreatedAt
  createdAt: Date;

  @UpdatedAt
  updatedAt: Date;

  @BelongsTo(() => Company)
  company: any;

  @BelongsTo(() => CrmLead)
  lead?: any;

  @BelongsTo(() => Cliente)
  cliente?: any;

  @BelongsTo(() => User)
  user: any;

  @BelongsTo(() => CrmTaskCategory)
  category?: any;

  @BelongsTo(() => CrmTaskStage)
  stage?: any;

  @BelongsTo(() => CrmTask, "parentTaskId")
  parentTask?: any;
}

export default CrmTask;
