import * as Yup from "yup";
import AppError from "../../errors/AppError";
import CrmTask from "../../models/CrmTask";
import { addMonths, addYears, startOfDay } from "date-fns";

interface Request {
  leadId?: number | string;
  clienteId?: number | string;
  userId: number | string;
  categoryId?: number | string;
  stageId?: number | string;
  title: string;
  description?: string;
  dueDate?: Date | string;
  status?: string;
  priority?: string;
  companyId: number | string;
  recurrence?: string;
  reminderDays?: number | string;
}

const CreateService = async (data: Request): Promise<CrmTask> => {
  const schema = Yup.object().shape({
    title: Yup.string().required().min(2),
    userId: Yup.number().required()
  });

  try {
    await schema.validate({ 
      title: data.title,
      userId: data.userId 
    });
  } catch (err: any) {
    throw new AppError(err.message);
  }

  // Validar que pelo menos leadId ou clienteId foi fornecido
  if (!data.leadId && !data.clienteId) {
    throw new AppError("É necessário informar um Lead ou Cliente para a tarefa");
  }

  // Limpar e converter valores vazios para null
  const cleanLeadId = data.leadId && data.leadId !== "" ? parseInt(String(data.leadId)) : null;
  const cleanClienteId = data.clienteId && data.clienteId !== "" ? parseInt(String(data.clienteId)) : null;
  const cleanCategoryId = data.categoryId && data.categoryId !== "" ? parseInt(String(data.categoryId)) : null;
  const cleanStageId = data.stageId && data.stageId !== "" ? parseInt(String(data.stageId)) : null;
  const cleanReminderDays = data.reminderDays && data.reminderDays !== "" ? parseInt(String(data.reminderDays)) : null;
  const cleanDueDate = data.dueDate && !isNaN(new Date(data.dueDate).getTime()) ? data.dueDate : null;

  // Calcular nextOccurrence se for recorrente
  let nextOccurrence = null;
  if (data.recurrence && cleanDueDate) {
    const baseDate = startOfDay(new Date(cleanDueDate));
    
    switch (data.recurrence) {
      case "monthly":
        nextOccurrence = addMonths(baseDate, 1);
        break;
      case "quarterly":
        nextOccurrence = addMonths(baseDate, 3);
        break;
      case "semiannual":
        nextOccurrence = addMonths(baseDate, 6);
        break;
      case "annual":
        nextOccurrence = addYears(baseDate, 1);
        break;
    }
  }

  const task = await CrmTask.create({
    companyId: data.companyId,
    leadId: cleanLeadId,
    clienteId: cleanClienteId,
    userId: data.userId,
    categoryId: cleanCategoryId,
    stageId: cleanStageId,
    title: data.title,
    description: data.description || null,
    dueDate: cleanDueDate,
    status: data.status || "pending",
    priority: data.priority || "medium",
    recurrence: data.recurrence || null,
    reminderDays: cleanReminderDays,
    isAutoGenerated: false,
    nextOccurrence
  });

  await task.reload({
    include: [
      { association: "user" },
      { association: "category" },
      { association: "stage" },
      { association: "lead" },
      { association: "cliente" }
    ]
  });

  return task;
};

export default CreateService;
