import __cjs_sequelize from "sequelize";
const { QueryInterface, DataTypes } = __cjs_sequelize;
module.exports = {
  up: (queryInterface: QueryInterface) => {
    return Promise.all([
      // Campo de recorrência: null (não recorrente), monthly, quarterly, semiannual, annual
      queryInterface.addColumn("CrmTasks", "recurrence", {
        type: DataTypes.STRING(20),
        allowNull: true,
        defaultValue: null
      }),
      
      // ID da tarefa pai (para rastrear tarefas geradas automaticamente)
      queryInterface.addColumn("CrmTasks", "parentTaskId", {
        type: DataTypes.INTEGER,
        references: { model: "CrmTasks", key: "id" },
        onUpdate: "CASCADE",
        onDelete: "SET NULL",
        allowNull: true
      }),
      
      // Data da próxima ocorrência (para o job processar)
      queryInterface.addColumn("CrmTasks", "nextOccurrence", {
        type: DataTypes.DATE,
        allowNull: true
      }),
      
      // Dias antes para notificar (lembrete)
      queryInterface.addColumn("CrmTasks", "reminderDays", {
        type: DataTypes.INTEGER,
        allowNull: true,
        defaultValue: null
      }),
      
      // Se a tarefa é gerada automaticamente
      queryInterface.addColumn("CrmTasks", "isAutoGenerated", {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: false
      })
    ]);
  },

  down: (queryInterface: QueryInterface) => {
    return Promise.all([
      queryInterface.removeColumn("CrmTasks", "recurrence"),
      queryInterface.removeColumn("CrmTasks", "parentTaskId"),
      queryInterface.removeColumn("CrmTasks", "nextOccurrence"),
      queryInterface.removeColumn("CrmTasks", "reminderDays"),
      queryInterface.removeColumn("CrmTasks", "isAutoGenerated")
    ]);
  }
};
