import __cjs_sequelize from "sequelize";
const { Op } = __cjs_sequelize;
import CrmTask from "../../models/CrmTask";
import { startOfDay, addMonths, addYears } from "date-fns";

interface Request {
  companyId?: number;
}

const ProcessRecurringTasksService = async ({ companyId }: Request): Promise<number> => {
  const today = startOfDay(new Date());
  
  // Buscar tarefas recorrentes que precisam gerar nova ocorrência
  const whereCondition: any = {
    recurrence: {
      [Op.not]: null
    },
    [Op.or]: [
      {
        nextOccurrence: {
          [Op.lte]: today
        }
      },
      {
        nextOccurrence: null,
        completedAt: {
          [Op.not]: null
        }
      }
    ]
  };

  if (companyId) {
    whereCondition.companyId = companyId;
  }

  const recurringTasks = await CrmTask.findAll({
    where: whereCondition,
    include: [
      { association: "company" },
      { association: "user" },
      { association: "category" }
    ]
  });

  let tasksCreated = 0;

  for (const task of recurringTasks) {
    try {
      // Calcular próxima data baseada na recorrência
      const baseDate = task.nextOccurrence || task.completedAt || task.dueDate;
      let nextDate: Date;

      switch (task.recurrence) {
        case "monthly":
          nextDate = addMonths(baseDate, 1);
          break;
        case "quarterly":
          nextDate = addMonths(baseDate, 3);
          break;
        case "semiannual":
          nextDate = addMonths(baseDate, 6);
          break;
        case "annual":
          nextDate = addYears(baseDate, 1);
          break;
        default:
          continue;
      }

      // Criar nova tarefa
      await CrmTask.create({
        companyId: task.companyId,
        leadId: task.leadId,
        clienteId: task.clienteId,
        userId: task.userId,
        categoryId: task.categoryId,
        title: task.title,
        description: task.description,
        dueDate: nextDate,
        status: "pending",
        priority: task.priority || "medium",
        recurrence: null, // A tarefa gerada não é recorrente
        parentTaskId: task.id,
        isAutoGenerated: true,
        reminderDays: task.reminderDays
      });

      // Atualizar próxima ocorrência da tarefa pai
      await task.update({
        nextOccurrence: nextDate
      });

      tasksCreated++;
    } catch (error) {
      console.error(`Erro ao processar tarefa recorrente ${task.id}:`, error);
    }
  }

  return tasksCreated;
};

export default ProcessRecurringTasksService;
